name: Good Morning Bot

on:
  schedule:
    - cron: '0 1 * * *'  # Everyday at 7 AM Bangladesh time (UTC+6 = 1 AM UTC)
  workflow_dispatch:

jobs:
  post_good_morning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install python-telegram-bot requests

    - name: Run bot script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
      run: python main.py
